<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSettingsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('settings', function (Blueprint $table) {
            $table->increments('id');
            $table->string('website_name', 200)->nullable();
            $table->string('website_title', 100)->nullable();
            $table->text('website_description')->nullable();
            $table->string('website_keywords', 200)->nullable();
            $table->string('theme', 100)->nullable();
            $table->string('paypal_email', 100)->nullable();
            $table->integer('subscription_price')->nullable();
            $table->string('subscription_currency', 20)->nullable();
            $table->string('subscription_name', 100)->nullable();
            $table->string('disquis_short_name', 50)->nullable();
            $table->integer('footer_on_content_optimized_pages')->nullable();
            $table->string('redirect_after_login', 100)->nullable();
            $table->string('default_language', 50)->nullable();
            $table->string('facebook_url', 100)->nullable();
            $table->string('twitter_url', 100)->nullable();
            $table->integer('show_actors')->nullable();
            $table->integer('supports_starring')->nullable();
            $table->integer('kid_profiles')->nullable();
            $table->integer('show_profiles')->nullable();
            $table->integer('supports_profiles')->nullable();
            $table->string('jwplayer_key', 100)->nullable();

            $table->timestamps();
        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('settings');
    }
}
