<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateEpisodesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('episodes', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('season_id');
            $table->integer('movie_id');
            $table->integer('episode_number')->nullable();
            $table->string('episode_name', 200)->nullable();
            $table->text('episode_description')->nullable();
            $table->string('episode_thumbnail', 200)->nullable();
            $table->text('episode_source')->nullable();
            $table->integer('is_embed')->nullable();

            $table->timestamps();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('episodes');
    }
}
