<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMoviesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('movies', function (Blueprint $table) {
            $table->increments('id');
            $table->string('movie_name', 200);
            $table->text('movie_plot')->nullable();
            $table->text('movie_year')->nullable();
            $table->string('movie_genres', 200)->nullable();
            $table->string('movie_poster_image', 200)->nullable();
            $table->string('movie_thumb_image', 200)->nullable();
            $table->integer('movie_plays')->nullable();
            $table->text('movie_source')->nullable();
            $table->integer('is_embed')->nullable();
            $table->integer('is_featured')->nullable();
            $table->integer('is_series')->nullable();
            $table->integer('last_season')->nullable();
            $table->integer('is_kid_friendly')->nullable();
            $table->integer('free_to_watch')->nullable();

            $table->timestamps();

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('movies');
    }
}
